use_frameworks!

target 'HuayingStatefulViewMachine_Example' do
  pod 'HuayingStatefulViewMachine', :path => '../'

  target 'HuayingStatefulViewMachine_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
